### PR TITLE
ReGameDLL API: Add PM_UpdateStepSound

### LINKED ISSUE #90: [Bug] Wrong m_iTotalRoundsPlayed value in 1st HLTV event
Hello. After the restart / Game Commencing in the first round, HLTV event returns m_iTotalRoundsPlayed value 1, Round_Start event returns 0.

```
L 12/24/2016 - 20:37:58: [test.amxx] func: Start | rounds_num = 0
L 12/24/2016 - 20:38:07: [test.amxx] func: GCommencing | rounds_num = 0
L 12/24/2016 - 20:38:07: [test.amxx] func: End | rounds_num = 0
L 12/24/2016 - 20:38:10: [test.amxx] func: HLTV | rounds_num = 1
L 12/24/2016 - 20:38:10: [test.amxx] func: Start | rounds_num = 0
L 12/24/2016 - 20:38:47: [test.amxx] func: Restart | rounds_num = 0
L 12/24/2016 - 20:38:48: [test.amxx] func: HLTV | rounds_num = 1
L 12/24/2016 - 20:38:48: [test.amxx] func: Start | rounds_num = 0
L 12/24/2016 - 20:39:55: [test.amxx] func: End | rounds_num = 0
L 12/24/2016 - 20:40:00: [test.amxx] func: HLTV | rounds_num = 1
L 12/24/2016 - 20:40:00: [test.amxx] func: Start | rounds_num = 1
L 12/24/2016 - 20:42:30: [test.amxx] func: End | rounds_num = 1
L 12/24/2016 - 20:42:35: [test.amxx] func: HLTV | rounds_num = 2
L 12/24/2016 - 20:42:35: [test.amxx] func: Start | rounds_num = 2
```
```
#include <amxmodx> 
#include <reapi> 

#pragma semicolon 1 

#define get_rounds get_member_game(m_iTotalRoundsPlayed) 

public plugin_init() { 
    register_event("HLTV", "HLTV", "a", "1=0", "2=0"); 
    register_logevent("Start", 2, "1=Round_Start"); 
    register_logevent("GCommencing", 2, "1=Game_Commencing"); 
    register_logevent("End", 2, "1=Round_End"); 
    register_logevent("Restart", 2, "1&Restart_Round_"); 
} 

public HLTV() { 
    log_amx("func: HLTV | rounds_num = %d", get_rounds); 
} 

public Start() { 
    log_amx("func: Start | rounds_num = %d", get_rounds); 
} 

public GCommencing() { 
    log_amx("func: GCommencing | rounds_num = %d", get_rounds); 
} 

public End() { 
    log_amx("func: End | rounds_num = %d", get_rounds); 
} 

public Restart() { 
    log_amx("func: Restart | rounds_num = %d", get_rounds); 
} 
```

### PR DESCRIPTION
**Pull request by Adidasman1**
Fixes #90
Fix: not ending of the round when the hostages rescued

### CODE REVIEW

File: regamedll/dlls/multiplay_gamerules.cpp [hunk 1]
```diff
@@ -1810,6 +1809,10 @@ void EXT_FUNC CHalfLifeMultiplay::__API_VHOOK(RestartRound)()
 			TheBots->OnEvent(EVENT_NEW_MATCH);
 		}
 	}
+	else
+	{
+		m_iTotalRoundsPlayed++;
```
Comment (WPMGPRoSToTeMa) [inline regamedll/dlls/multiplay_gamerules.cpp]: Should this be in fixed macro?
