### PR TITLE
Fix excessive punchangle when getting shield shot

### LINKED ISSUE #918: FireBullets3. punchangle for SHIELD
https://github.com/s1lentq/ReGameDLL_CS/blob/15df1a9cf2e6a9afe284556a23af83d007926cb6/regamedll/dlls/cbase.cpp#L1452-L1455

`pEntity->pev->punchangle.x = 4; ?`

### PR DESCRIPTION
**Pull request by dystopm**
Fixes #918 - it demonstrates how abrupt punchangle change was done when getting shot using tactical shield.

### CODE REVIEW

File: regamedll/dlls/cbase.cpp [hunk 1]
```diff
@@ -1449,7 +1449,11 @@ VectorRef CBaseEntity::__API_HOOK(FireBullets3)(VectorRef vecSrc, VectorRef vecD
 				pEntity->pev->punchangle.x = iCurrentDamage * RANDOM_FLOAT(-0.15, 0.15);
 				pEntity->pev->punchangle.z = iCurrentDamage * RANDOM_FLOAT(-0.15, 0.15);
 
+#ifndef REGAMEDLL_FIXES
```
Comment (wopox1337) [inline regamedll/dlls/cbase.cpp:1452]:
```suggestion
#ifdef REGAMEDLL_FIXES
				pEntity->pev->punchangle.x = clamp(pEntity->pev->punchangle.x, -4, 4)
				pEntity->pev->punchangle.z = clamp(pEntity->pev->punchangle.x, -5, 5)
#else
				if (pEntity->pev->punchangle.x < 4)
					pEntity->pev->punchangle.x = -4;

				if (pEntity->pev->punchangle.z < -5)
					pEntity->pev->punchangle.z = -5;
				else if (pEntity->pev->punchangle.z > 5)
					pEntity->pev->punchangle.z = 5;
#endif
```

Comment (wopox1337) [reply regamedll/dlls/cbase.cpp:1452]: It looks more logical that way, but I can't be sure of this solution.

**Review by wopox1337 — CHANGES_REQUESTED** [review]
